#!/usr/bin/env groovy
pipeline {
    agent any
    triggers { pollSCM('*/2 * * * *') }

    // stages {
    //     stage ('print branch name') {
    //         steps {
    //             echo BRANCH_NAME
    //             CommitStatus createStatus(String status [ "Fail", "it fail test", String targetUrl])  
    //         }
    //     }
    // }
    script {
        public CommitStatus createStatus(IRepositoryIdProvider repository,
                String sha, CommitStatus status) throws IOException {
            commitStatus.put(sha, status);

            return status;
            }
    }
}

 